### ISSUE TITLE
咨询一个小问题，JPEG压缩使用的什么库呀

### ISSUE THREAD

**Issue by cesaryuan** [joye61/pic-smaller#11]
我看到在Thanks里面列出了Gif、PNG、avif使用的压缩库，那JPEG使用的什么库呀😊

**Comment by joye61** [comment]
小技巧，浏览器原生支持JPEG/WEBP压缩，使用简单且效果非常不错，图小小底层用的就是这个功能，参考[HTMLCanvasElement: toBlob()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob)
