### ISSUE TITLE
Can't output to gif

### ISSUE THREAD

**Issue by dwonderg** [joye61/pic-smaller#18]
![image](https://github.com/joye61/pic-smaller/assets/160792706/01cc5d43-728c-4684-95e5-0835750f67b2)

**Comment by dwonderg** [comment]
GIF output not on the list!

**Comment by joye61** [comment]
Vector types (like SVG) and animation types (like GIF) are not supported as output target currently  https://github.com/joye61/pic-smaller/issues/3#issuecomment-2129771443

**Comment by dwonderg** [comment]
GIF output was working before!? Why change?

**Comment by dwonderg** [comment]
🥱
