### ISSUE TITLE
调整图片尺寸添加“设置长边，短边自动缩放”

### ISSUE THREAD

**Issue by Usr-Unavailable** [joye61/pic-smaller#27]
如题，批量操作中很多时候是同一批次的摄影，有些是纵向的有些是横向的。如果能添加如题功能，可以有效提高操作效率。

**Comment by joye61** [comment]
> 如题，批量操作中很多时候是同一批次的摄影，有些是纵向的有些是横向的。如果能添加如题功能，可以有效提高操作效率。

你的意思是长边设置一个固定值，短边可以根据这个固定值等比例缩放吗？这个长边既可以是宽度，也可以是高度？

**Comment by Usr-Unavailable** [comment]
是这么一个理解
