### ISSUE TITLE
质量调整选项太少

### ISSUE THREAD

**Issue by wangyjx** [joye61/pic-smaller#3]
可以参考一下squoosh.app
看看提供了多少调整选项，以及还可以进行格式转换

**Comment by muzilong** [comment]
感谢作者的付出，图小小特别棒。
期待把格式转换这个功能加上，再次感谢您。

**Comment by joye61** [comment]
已完成图片格式转换的支持，但有一些限制：

1. 不支持到GIF/SVG格式的转换
2. 带透明背景的图片转换到AVIF格式目前有黑底
3. 大尺寸图片转换到AVIF格式速度有点慢

Support for image format conversion has been completed, but there are some limitations:

1. Conversion to GIF/SVG format is not supported
2. Images with transparent backgrounds converted to AVIF format currently have black backgrounds.
3. Converting large-size pictures to AVIF format is a bit slow

**Comment by joye61** [comment]
> 感谢作者的付出，图小小特别棒。 期待把格式转换这个功能加上，再次感谢您。

已完成图片格式转换的支持，但有一些限制：

1. 不支持到GIF/SVG格式的转换
2. 带透明背景的图片转换到AVIF格式目前有黑底
3. 大尺寸图片转换到AVIF格式速度有点慢


Support for image format conversion has been completed, but there are some limitations:

1. Conversion to GIF/SVG format is not supported
2. Images with transparent backgrounds converted to AVIF format currently have black backgrounds.
3. Converting large-size pictures to AVIF format is a bit slow

**Comment by muzilong** [comment]
效率好高，太惊喜了，谢谢您。
