### ISSUE TITLE
提个建议, 增加 api 给命令行调用

### ISSUE THREAD

**Issue by yangxuan0261** [joye61/pic-smaller#37]
RT, 方便构建 h5 游戏后使用脚本调用 api 自动压缩等需要自动化压缩的情况

**Comment by joye61** [comment]
很抱歉，目前无法实现。图小小是个完全面向浏览器的应用，依赖多个浏览器的原生API，增加API给命令行调用需要大量改动。不过这里有一个思路，可以通过Headless Browser的方式，如 https://pptr.dev/ 或者 https://playwright.dev/ ，但这种方式会导致 cli 依赖体积巨大，实现并不优雅。你可以自行尝试实现，目前我没有这样的精力和计划，很抱歉
