### ISSUE TITLE
我使用后图片变大了。

### ISSUE THREAD

**Issue by maxcodecode** [joye61/pic-smaller#38]
![1](https://github.com/joye61/pic-smaller/assets/173876447/11654003-5e00-4882-85e3-98240c372448)
看下结果。
![10005ys](https://github.com/joye61/pic-smaller/assets/173876447/163e11db-3b23-47d4-8b7b-07616fa95b77)
zhe这是原图。你自己可以试下。

**Comment by joye61** [comment]
由于默认是批量压缩，无法保证默认参数能满足所有图片都被压缩，比方说你在其他工具已经压缩过的图片，放这里再次压缩很有可能会变大，这确实是一个工具缺陷，你可以调整JPEG格式的压缩参数（比方说0.5），图片就能变得更小。

图片压缩其实是一个重新编码的过程，所有的类型压缩都是基于原生接口或第三方库，工具本身没有实现编码，我没研究那么深，所以其实我也不会。
