### ISSUE TITLE
为何有些图片压缩之后反而变大了

### ISSUE THREAD

**Issue by dufu1991** [joye61/pic-smaller#5]
<img width="1532" alt="image" src="https://github.com/joye61/pic-smaller/assets/24769077/2daecbaf-599b-4455-9e81-d92e3b099058">

如上图所示。

**Comment by joye61** [comment]
所有的压缩都会对图片重新编码，如果已经没有压缩空间，会生成更大的图。你可以尝试调整JPEG压缩质量选项，参数值越小，输出图片越小，但要注意所有的压缩都是有损压缩，可以试着调整不同的参数值，尽量达到自己满意的效果

**Comment by vimiix** [comment]
> 所有的压缩都会对图片重新编码，如果已经没有压缩空间，会生成更大的图。你可以尝试调整JPEG压缩质量选项，参数值越小，输出图片越小，但要注意所有的压缩都是有损压缩，可以试着调整不同的参数值，尽量达到自己满意的效果

不妨在代码里判断比较一下处理前后的大小，如果处理后反而变大了，大可以丢弃，然后在界面上提示: ”已经无法更小了“（或者 ”调整参数后重试“ 之类）这样体验感觉会好些，毕竟这个产品的功能应该只关注尺寸减小的方向。

**Comment by joye61** [comment]
已采纳
