### ISSUE TITLE
怎么编译部署到二级目录呢

### ISSUE THREAD

**Issue by mu0641** [joye61/pic-smaller#8]
你好，请问怎么编译部署到二级目录呢？

**Comment by joye61** [comment]
目前项目已支持部署到子目录，这里假设你的二级目录是`/sub`：

1. 修改根目录下`vite.config.js`的`base`参数值为`/sub`
2. 执行`npm run build`生成`dist`目录，`dist`目录即为支持二级目录的SPA应用
3. 由于前端History路由的使用， 需要将`dist/index.html`配置为二级目录`/sub`的单一入口
    3.1.  通过服务器配置`dist/index.html`为`/sub`子**路径**的单一入口，也就是说无论访问`/sub`、`/sub/path`、`/sub/path/to`、`/sub/index.html`都应该指向`dist/index.html`
    3.2. 单一入口仅对路径配置，对于图片、字体、CSS、JS等静态资源保留完整访问路径即可，也就是说 `/sub/to/test.js`、`/sub/to/test.css`、`/sub/to/test.png`等静态资源必须保持原始路径

请注意单一入口配置仅针对路径，静态资源保持原始路径即可，任意N级目录的配置同理，这里不再赘述
